CREATE TABLE TASK (taskId INTEGER PRIMARY KEY, TITLE TEXT,
LATITUDE INTEGER,
LONGITUDE INTEGER,
ADDRESS TEXT,
ENABLEADDRESS boolean,
ADDRESSVERIFIED boolean,
DATE TEXT,
HOUR INTEGER,
MINUTE INTEGER);
